In [ ]:
import pandas as pd

In [ ]:
df=pd.read_csv('https://raw.githubusercontent.com/JuliaData/CSV.jl/refs/heads/main/test/testfiles/Sacramentorealestatetransactions.csv')
df.head(5)

,street,city,zip,state,beds,baths,sq__ft,type,sale_date,price,latitude,longitude
0,3526 HIGH ST,SACRAMENTO,95838,CA,2,1,836,Residential,Wed May 21 00:00:00 EDT 2008,59222,38.631913,-121.434879
1,51 OMAHA CT,SACRAMENTO,95823,CA,3,1,1167,Residential,Wed May 21 00:00:00 EDT 2008,68212,38.478902,-121.431028
2,2796 BRANCH ST,SACRAMENTO,95815,CA,2,1,796,Residential,Wed May 21 00:00:00 EDT 2008,68880,38.618305,-121.443839
3,2805 JANETTE WAY,SACRAMENTO,95815,CA,2,1,852,Residential,Wed May 21 00:00:00 EDT 2008,69307,38.616835,-121.439146
4,6001 MCMAHON DR,SACRAMENTO,95824,CA,2,1,797,Residential,Wed May 21 00:00:00 EDT 2008,81900,38.519470,-121.435768

## Number of the columns in the data frame

In [ ]:
df.columns

Index(['street', 'city', 'zip', 'state', 'beds', 'baths', 'sq__ft', 'type',
       'sale_date', 'price', 'latitude', 'longitude'],
      dtype='object')

In [ ]:
no_of_cols = len(df.columns)
no_of_cols

12

## Mean of the house prices

In [ ]:
price_mean = df['price'].mean()
price_mean

np.float64(234144.26395939087)

## Median of the house prices

In [ ]:
price_median = df['price'].median()
price_median

213750.0

## Different types of property in the dataset

In [ ]:
diff_prop = df['type'].unique()
diff_prop

array(['Residential', 'Condo', 'Multi-Family', 'Unkown'], dtype=object)

## Maximum price of a "Condo" in the dataset

In [ ]:
max_condo_price = df.loc[df['type'] == 'Condo', 'price'].max()
max_condo_price

360000

## Mean price of each type of property in the dataset

In [ ]:
df.groupby('type')['price'].mean()

type
Condo           150082.185185
Multi-Family    224534.692308
Residential     239186.162486
Unkown          275000.000000
Name: price, dtype: float64

## Count of different property types in dataset

In [ ]:
df.groupby('type').size()

type
Condo            54
Multi-Family     13
Residential     917
Unkown            1
dtype: int64